import type { Product } from "./types";

const products: Product[] = [
  {
    id: "1",
    name: "Cuenta Básica",
    type: "Cuenta",
    category: "Personal",
    description:
      "Cuenta de ahorro sin comisiones con tarjeta de débito incluida.",
    interestRate: 0.5,
    term: "N/A",
    benefits: [
      "Sin comisión por mantenimiento",
      "Tarjeta de débito sin costo",
      "Retiros ilimitados en cajeros propios",
      "Banca en línea 24/7",
    ],
    performanceData: {
      labels: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      values: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
    },
  },
  {
    id: "2",
    name: "Cuenta Premium",
    type: "Cuenta",
    category: "Tarjetas",
    description: "Cuenta con beneficios exclusivos y mayores tasas de interés.",
    interestRate: 1.2,
    term: "N/A",
    benefits: [
      "Tasa de interés preferencial",
      "Tarjeta de débito premium",
      "Retiros sin costo en cualquier cajero",
      "Atención prioritaria",
      "Seguros incluidos",
    ],
    performanceData: {
      labels: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      values: [1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2],
    },
  },
  {
    id: "3",
    name: "Fondo Conservador",
    type: "Inversión",
    category: "Fondos",
    description: "Fondo de inversión con bajo riesgo y rendimientos estables.",
    interestRate: 3.5,
    riskLevel: 2,
    term: "1-3 años",
    minimumAmount: 1000,
    benefits: [
      "Bajo riesgo",
      "Liquidez en 48 horas",
      "Diversificación automática",
      "Sin comisión por retiro",
    ],
    performanceData: {
      labels: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      values: [
        100, 101.2, 102.5, 103.1, 104.2, 105.0, 106.3, 107.1, 108.2, 109.0,
        110.5, 111.8,
      ],
    },
  },
  {
    id: "4",
    name: "Fondo Crecimiento",
    type: "Inversión",
    category: "Fondos",
    description:
      "Fondo de inversión con riesgo moderado y potencial de crecimiento.",
    interestRate: 6.8,
    riskLevel: 3,
    term: "3-5 años",
    minimumAmount: 5000,
    benefits: [
      "Diversificación en múltiples sectores",
      "Gestión activa del portafolio",
      "Reportes trimestrales detallados",
      "Asesoría personalizada",
    ],
    performanceData: {
      labels: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      values: [
        100, 102.5, 101.8, 104.2, 107.5, 106.3, 109.8, 112.4, 110.5, 115.2,
        118.7, 121.3,
      ],
    },
  },
  {
    id: "5",
    name: "Fondo Agresivo",
    type: "Inversión",
    category: "Tarjetas",
    description:
      "Fondo de inversión de alto riesgo con potencial de altos rendimientos.",
    interestRate: 12.5,
    riskLevel: 5,
    term: "5+ años",
    minimumAmount: 10000,
    benefits: [
      "Exposición a mercados internacionales",
      "Potencial de alto rendimiento",
      "Gestión por expertos en mercados globales",
      "Acceso a IPOs exclusivas",
    ],
    performanceData: {
      labels: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      values: [
        100, 105.2, 98.7, 107.3, 115.8, 112.4, 120.5, 128.7, 122.3, 132.5,
        140.8, 148.2,
      ],
    },
  },
  {
    id: "6",
    name: "Tarjeta Clásica",
    type: "Tarjeta",
    category: "Personal",
    description:
      "Tarjeta de crédito con beneficios básicos y tasa competitiva.",
    interestRate: 28.9,
    term: "N/A",
    benefits: [
      "Sin anualidad el primer año",
      "Programa de puntos básico",
      "Seguro de compras",
      "Asistencia en viajes",
    ],
    performanceData: {
      labels: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      values: [
        28.9, 28.9, 28.9, 28.9, 28.9, 28.9, 28.9, 28.9, 28.9, 28.9, 28.9, 28.9,
      ],
    },
  },
  {
    id: "7",
    name: "Tarjeta Oro",
    type: "Tarjeta",
    category: "Personal",
    description:
      "Tarjeta de crédito con beneficios mejorados y límites más altos.",
    interestRate: 26.5,
    term: "N/A",
    benefits: [
      "Programa de recompensas mejorado",
      "Acceso a salas VIP en aeropuertos (2 visitas/año)",
      "Seguro de viaje extendido",
      "Protección de precio en compras",
    ],
    performanceData: {
      labels: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      values: [
        26.5, 26.5, 26.5, 26.5, 26.5, 26.5, 26.5, 26.5, 26.5, 26.5, 26.5, 26.5,
      ],
    },
  },
  {
    id: "8",
    name: "Tarjeta Platinum",
    type: "Tarjeta",
    category: "Tarjetas",
    description:
      "Tarjeta de crédito premium con beneficios exclusivos y servicio prioritario.",
    interestRate: 24.9,
    term: "N/A",
    benefits: [
      "Concierge personal 24/7",
      "Acceso ilimitado a salas VIP en aeropuertos",
      "Seguro médico internacional",
      "Protección extendida en compras",
      "Experiencias exclusivas",
    ],
    performanceData: {
      labels: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      values: [
        24.9, 24.9, 24.9, 24.9, 24.9, 24.9, 24.9, 24.9, 24.9, 24.9, 24.9, 24.9,
      ],
    },
  },
  {
    id: "9",
    name: "Préstamo Personal",
    type: "Préstamo",
    category: "Personal",
    description:
      "Préstamo de libre disposición con tasa fija y plazos flexibles.",
    interestRate: 16.9,
    term: "12-60 meses",
    minimumAmount: 1000,
    benefits: [
      "Sin comisión por apertura",
      "Aprobación en 24 horas",
      "Pago anticipado sin penalización",
      "Cuotas fijas durante todo el plazo",
    ],
    performanceData: {
      labels: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      values: [
        16.9, 16.9, 16.9, 16.9, 16.9, 16.9, 16.9, 16.9, 16.9, 16.9, 16.9, 16.9,
      ],
    },
  },
  {
    id: "10",
    name: "Hipoteca Estándar",
    type: "Hipoteca",
    category: "Personal",
    description:
      "Financiamiento para la compra de vivienda con tasas competitivas.",
    interestRate: 8.5,
    term: "5-30 años",
    minimumAmount: 50000,
    benefits: [
      "Financiamiento hasta el 80% del valor",
      "Tasa fija los primeros 5 años",
      "Seguro de desempleo incluido",
      "Asesoría inmobiliaria gratuita",
    ],
    performanceData: {
      labels: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      values: [8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5],
    },
  },
  {
    id: "11",
    name: "Seguro de Vida",
    type: "Seguro",
    category: "Personal",
    description:
      "Protección financiera para tus seres queridos en caso de fallecimiento.",
    term: "Anual renovable",
    minimumAmount: 100,
    benefits: [
      "Cobertura desde el primer día",
      "Indemnización por fallecimiento o invalidez",
      "Asistencia funeraria",
      "Trámites simplificados para beneficiarios",
    ],
    performanceData: {
      labels: [
        "Año 1",
        "Año 2",
        "Año 3",
        "Año 4",
        "Año 5",
        "Año 6",
        "Año 7",
        "Año 8",
        "Año 9",
        "Año 10",
      ],
      values: [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
    },
  },
  {
    id: "12",
    name: "Plan de Retiro",
    type: "Inversión",
    category: "Personal",
    description: "Plan de ahorro a largo plazo para asegurar tu jubilación.",
    interestRate: 5.2,
    riskLevel: 2,
    term: "Hasta la jubilación",
    minimumAmount: 500,
    benefits: [
      "Beneficios fiscales",
      "Aportaciones flexibles",
      "Estrategia de inversión ajustada a tu edad",
      "Proyecciones personalizadas de retiro",
    ],
    performanceData: {
      labels: [
        "Año 1",
        "Año 5",
        "Año 10",
        "Año 15",
        "Año 20",
        "Año 25",
        "Año 30",
        "Año 35",
        "Año 40",
      ],
      values: [100, 128, 165, 213, 275, 354, 456, 588, 758],
    },
  },
];

export function getAllProducts(): Product[] {
  return products;
}

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((product) => product.category === category);
}

export function getProductsByType(type: string): Product[] {
  return products.filter((product) => product.type === type);
}
